import json from '@rollup/plugin-json';
import commonjs from '@rollup/plugin-commonjs';

export default [
	{
		input: 'src/request.dev.js',
		output: {
			file: 'dist/request.dev.js',
			format: 'es',
			banner: '/* Request Script (Dev) - Generated by Rollup */',
		},
		plugins: [json(), commonjs()]
	},
	{
		input: 'src/response.dev.js',
		output: {
			file: 'dist/response.dev.js',
			format: 'es',
			banner: '/* Response Script (Dev) - Generated by Rollup */',
		},
		plugins: [json(), commonjs()]
	},
];
