import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';

export default [
  {
    input: 'src/request.js',
    output: {
      file: 'dist/request.js',
      format: 'es',
      banner: '/* Request Script - Generated by Rollup */',
    },
    plugins: [
      nodeResolve(),
      commonjs(),
    ],
    external: ['@nsnanocat/util', '@nsnanocat/url', '@nsnanocat/grpc'],
  },
  {
    input: 'src/response.js',
    output: {
      file: 'dist/response.js',
      format: 'es',
      banner: '/* Response Script - Generated by Rollup */',
    },
    plugins: [
      nodeResolve(),
      commonjs(),
    ],
    external: ['@nsnanocat/util', '@nsnanocat/url', '@nsnanocat/grpc'],
  },
];
