import json from '@rollup/plugin-json';
import commonjs from '@rollup/plugin-commonjs';
import terser from '@rollup/plugin-terser';

export default [
	{
		input: 'src/request.js',
		output: {
			file: 'js/request.js',
			format: 'es',
			banner: '/* Request Script - Generated by Rollup */',
		},
		plugins: [json(), commonjs(), terser()]
	},
	{
		input: 'src/response.js',
		output: {
			file: 'js/response.js',
			format: 'es',
			banner: '/* Response Script - Generated by Rollup */',
		},
		plugins: [json(), commonjs(), terser()]
	},
];
