import json from '@rollup/plugin-json';
import commonjs from '@rollup/plugin-commonjs';

export default [
	{
		input: 'src/request.js',
		output: {
			file: 'dist/request.debug.js',
			format: 'es',
			banner: '/* Request Script (Debug) - Generated by Rollup */',
		},
		plugins: [json(), commonjs()]
	},
	{
		input: 'src/response.js',
		output: {
			file: 'dist/response.debug.js',
			format: 'es',
			banner: '/* Response Script (Debug) - Generated by Rollup */',
		},
		plugins: [json(), commonjs()]
	},
];
